name:             'Таверна Кузня'
title:            'Таверна Кузня'
description:      'Taverna Pivnaya Kuznica'
url: https://vasiliybologov.github.io/pivnayakuznica/
#markdown: redcarpet
markdown: kramdown

lsi: false
safe: true
source: /
incremental: false
highlighter: rouge

baseurl:          /

gist:
  - jekyll-sitemap
  - jekyll-paginate-v2
  
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

pagination:
  enabled: true
  per_page: 5
